using System;
using System.Collections.Generic;

namespace Tsukikage.XGTGCtrl2.XG
{
    public struct MidiProgramNumber : IEquatable<MidiProgramNumber>
    {
        public int Index { get; set; }
        public int BankMSB { get { return Index >> 16; } }
        public int ProgramNumber { get { return Index >> 8 & 0xFF; } }
        public int BankLSB { get { return Index & 0xFF; } }
        public string ProgramName { get { return GetToneName(this); } }

        public MidiProgramNumber(int msb, int lsb, int pgn)
            : this()
        {
            Index = msb << 16 | pgn << 8 | lsb;
        }

        public MidiProgramNumber(int index)
            : this()
        {
            Index = index;
        }

        public override int GetHashCode() { return Index; }
        public bool Equals(MidiProgramNumber other) { return other.Index == Index; }
        public override bool Equals(object obj) { return (obj is MidiProgramNumber) ? Equals((MidiProgramNumber)obj) : false; }

        static Dictionary<int, string> toneNameBank;
        static Dictionary<int, string> drumToneNameBank;
        static List<int> allTones;

        public static string GetToneName(MidiProgramNumber program)
        {
            string ret;
            if (toneNameBank.TryGetValue(program.Index, out ret)) { return ret; }
            return "";
        }

        public static string GetDrumToneName(int msb, int pgn, int note)
        {
            string ret;
            if (drumToneNameBank.TryGetValue(new MidiProgramNumber(msb, pgn, note).Index, out ret)) { return ret; }
            return "";
        }


        public static MidiProgramNumber FindSameMSBNextTone(MidiProgramNumber pg)
        {
            int index = allTones.BinarySearch(pg.Index + 1);
            if (index < 0) { index = ~index; }
            MidiProgramNumber g = new MidiProgramNumber(allTones[index]);
            if (g.BankMSB != pg.BankMSB) { return pg; }
            return g;
        }

        public static MidiProgramNumber FindSameMSBPreviousTone(MidiProgramNumber pg)
        {
            int index = allTones.BinarySearch(pg.Index - 1);
            if (index < 0) { index = ~index - 1; }
            MidiProgramNumber g = new MidiProgramNumber(allTones[index]);
            if (g.BankMSB != pg.BankMSB) { return pg; }
            return g;
        }

        public static void Init()
        //static MidiProgramNumber()
        {
            toneNameBank = new Dictionary<int, string>();
            allTones = new List<int>();
            allTones.Add(int.MinValue);
            allTones.Add(int.MaxValue);
            ParseMap(toneMapTsv, (m, l, p, name) =>
            {
                MidiProgramNumber mpn = new MidiProgramNumber(m, l, p);
                allTones.Add(mpn.Index);
                toneNameBank.Add(mpn.Index, name.PadRight(10));
            });
            allTones.Sort();

            drumToneNameBank = new Dictionary<int, string>();
            ParseMap(drumMapTsv, (m, p, t, name) =>
            {
                MidiProgramNumber mpn = new MidiProgramNumber(m, p, t);
                drumToneNameBank.Add(mpn.Index, name);
            });
        }

        static void ParseMap(string table, Action<int, int, int, string> func)
        {
            string[] lines = table.Split(new char[] { '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries);

            for (int i = 0; i < lines.Length; i++)
            {
                string line = lines[i];
                string[] elements = line.Split('\t');

                int msb, lsb;
                if (elements.Length >= 3 && int.TryParse(elements[0], out msb) && int.TryParse(elements[1], out lsb))
                {
                    for (int j = 0; j < elements.Length - 2; j++)
                    {
                        if (!string.IsNullOrEmpty(elements[j + 2]))
                        {
                            func(msb, lsb, j, elements[j + 2]);
                        }
                    }
                }
            }
        }


        static string toneMapTsv =
    @"
0	0	GrandP #	BriteP #	El.Grand	HnkyTonk	EPiano1#	EPiano2#	Harpsi.	Clavi #	Celesta	Glocken	MusicBox	Vibes	Marimba	Xylophon	TubulBel	Dulcimer	DrawOrg#	PercOrg#	RockOrg#	ChrchOrg	ReedOrgn	Acordion	Harmnica	TangoAc#	NylonGt#	SteelGt#	JazzGtr#	CleanGtr	MuteGtr#	Ovrdriv#	DistGtr#	GtrHarmo	AcoBass#	FngrBa #	PickBass	Frtless#	SlapBa1#	SlapBa2#	SynBass1	SynBass2	Violin #	Viola	Cello	Contrabs	TremStr#	Pizz.Str	Harp	Timpani	Strngs1#	Strngs2#	Syn Str1	Syn Str2	ChoirAah	VoiceOoh	SynVoice	Orch.Hit	Trumpet#	Trmbone#	Tuba	MuteTrp#	Fr. Horn	BrssSec#	SynBrss1	SynBrss2	SprnoSax	AltoSax#	TenorSax	Bari.Sax	Oboe #	Eng.Horn	Bassoon	Clarinet	Piccolo	Flute #	Recorder	PanFlut#	Bottle	Shakhchi	Whistle	Ocarina	SquareLd	Saw Ld	CaliopLd	Chiff Ld	CharanLd	Voice Ld	Fifth Ld	Bass&Ld	NewAgePd	Warm Pad	PolySyPd	ChoirPad	BowedPad	MetalPad	Halo Pad	SweepPad	Rain	SoundTrk	Crystal	Atmosphr	Bright	Goblins	Echoes	Sci-Fi	Sitar	Banjo	Shamisen	Koto	Kalimba	Bagpipe	Fiddle	Shanai	TnklBell	Agogo	SteelDrm	Woodblok	TaikoDrm	MelodTom	Syn Drum	RevCymbl	FretNoiz	BrthNoiz	Seashore	Tweet	Telphone	Helicptr	Applause	Gunshot
0	1	GrndPnoK	BritPnoK	ElGrPnoK	HnkyTnkK	El.Pno1K	El.Pno2K	Harpsi.K	Clavi K				Vibes K	MarimbaK
0	3		StBrtPno															StDrawOr																																S.Strngs	S.SlwStr			S.Choir									StBrsSec
0	6																																			PickBa2					MelloSBa																					FrHrSolo																				SquarLd2	Saw Ld 2
0	8																																									Slow Vln				SlwTrStr				Slow Str	LegatoSt	Memory														VgSprnSx																LMSquare	ThickSaw					FifthLdS																Echoes 2
0	12						ChoEPDcy																									DstRthmG									Seq Bass																LoFi Hit							Quack Br																																				SynDrCmp
0	14																																																	SfzStrgs													SfrzndBr																																					Popcorn				Echo Pan
0	16																									NylonGt2	SteelGt2												BrtSlpSp															Ch.Aahs2				Trumpet2		Tuba 2																													Big&Low		ThickPad
0	17																																																									BriteTrp																																	Soft Pad
0	18	MelloGrP				MelloEP1																						MelloGtr							FingrDrk					SynBa1Dk	ClkSynBa											Zephyr							Trmbone2				MildBrss		Soft Brs		ASax Lgt															Hollow	Dyna Saw								Sine Pad									TinyBell	WarmAtms
0	19																																								SynBa2Dk																																									Shroud	Digi Saw																		HollwRls
0	20		ResoBrtP																																					FastResB																								RezSynBr																			Big Lead														Shwimmer
0	21																																					CsmicSlp		TL66													TradeWnd
0	22																																						Wah Slap		Zealot
0	24																		70sPcOr1													DistGtr2								AcidBass										Arco Str														PolyBrss																			HeavySyn				SynthAah
0	25							Harpsi.2																		NylonGt3																																																									WaspySyn
0	26																																																																																		Mondo
0	27								ClaviWah																										FlangeBa			ResoSlap		ResoBass												Reso Str												SynBrss3																			RezzySaw														Converge		Prologue
0	28																																			MutePkBa				MtdPulsB																																																																			MuteBnjo
0	29																																							SlwAttck																								AnalgSfz
0	32		DtndBrtP	Det.CP80		Chor.EP1	Chor.EP2	HarpsiDt										DetDrwOr	DetPrcOr		ChurOrg3	ReedOrDt	AccordIt	Harmo. 2		NylnGtDt	StlGtrDt	Jazz Amp	ChorusGt		OdrvGtDt				FngrBaDt		Fretles2	PunchThm			SmthSynB													MelChoir				Warm Trp				FrHorn 2		JumpBrss																			DoublSaw																							DetSitar
0	33						DX Hard											60sDrOr1	Lite Org										ChoGtrLt								Fretles3
0	34						DXLegend											60sDrOr2																			Fretles4
0	35			Synth CP				Harpsi.3									Dulcimr2	70sDrOr1			ChurOrg2						12StrGtr					DistGtr3								Clv Bass							Pizz Oct			60sStrng		Syn Str3					OrchHit2						Tp&TbSec																			2 Osc	Toy Lead					Big Five												RndGlock						Sitar 2
0	36																	DrawOrg2														PowerGt2																															Tp&TbSc2																				Dim Saw
0	37																	60sDrOr3	PercOrg2													PowerGt1																														HornOrch
0	38																	Even Bar														Dst.5ths
0	39																																																			Monarchy	WormHole	Gasp									BrssFall
0	40	PianoStr	SyPadPno	LayerCP1		HardEl.P	DX Phase	ElHarpsi	CsmcClav									16+22/3			NotreDam	Puff Org				Wayside	Nyln&Stl	OrganGtr		FunkGtr1	Parallel	FeedbkGt		JazzRthm	Ba&DstEG	PkB&MtGt				TechnoBa	ModulrBa	Unison	VlaDoubl			Susp.Str	Sleep	YangChin		Orchestr	Warm Str	GrandPad		ChoirStr		SyVoice2	Throne				Backyard		BrssSec2	SyBrsSub	SynBrss4		Sax Sect	BrthTnSx					Syn&Clr		NeatBrth								PulseSaw	Novice	SaltLead						Vishnu					Tiu				GlockChi	Nylon EP					Bhuj
0	41	Dream		LayerCP2			DX+Analg																				Stl&Body	OctPlate		MuteStlG		FeedbkG2		PckAcoBa						Kik'n'Ba	DX Bass									Orchstr2	Kingdom	SweepStr		Dead Sea		Choral							Hi Brass		ChoirBrs			SoftTenr															Dr.Lead																	ClearBel
0	42						DXKotoEP																									TwinDist								NEP	DXBa Brt									TremOrch		SwpStOct											MelloBrs		AnHrnRch																																			ChorBell
0	43																									VelGtHrm				FunkGtr2	Gt.Pinch	RckRthm2		Blink Ba	FngrSlap				VeloSlap										Roll&Hit																		HyprAlto
0	45					VX El.P1	VX El.P2						HardVibe																	Jazz Man		RckRthm1		VXUprght	FngBass2															Velo.Str														AnVelBr1	AnVelBr2																		VeloLead															ClaviPad
0	48						ChoEP K
0	52						DXMallet																																											Lento													Bund
0	53																																																														FakeHorn
0	54																																																														FkHrnOct
0	64	ConGrnd	BrConGrd			60sEl.P1	Shrakawa	SynHrpsi	PulseClv	FMCelsta		Orgel		SineMrmb				Organ Ba	JazOrgan	RotaryOr	OrgFlute	SyReedDk			TngoAcd2	EsGuitar	Nashvlle	SuperJzM	CleanGt2	Wrench	ManhttnM	Bite	AcoHarmo	Boston	Jazzy Ba	HardPick	PwrFrtls	Slapper		Orbiter	X WireBa	Cadenza	Sonata	CelloSec	CB Sec	Fear	Collegno	El.Harp		SprStrng	70s Str	Syn Str4	Hope	StrngAah	VoiceDoo	AnaVoice	Impact	Dark Trp	BrghtTrb	Hrd Tuba	MuteTrp2	Syn Horn	SprBrass	AnaBrss1	AnaBrss2	Mdtation	ASaxPwrd	TnrSax 2		Heinz					Boehm	Piplith	PanFlut2	BottlLgt		Reverie	Opalina	Mellow	Digger	Vent Syn	Rubby	DistLead	Vox Lead		Fat&Prky	Fantasy	Horn Pad	PolyPd80	Heaven	Glacier	Tine Pad	Aries	PolarPad	HrmoRain	Ancestrl	SynMalet	NylnHarp	FantaBel	GobSynth	EchoBell	Starz	Raga Syn	El Banjo		FM Koto	BigKalim	Thistle		Shanai 2	TcklBell					Mel Tom2	Ana Tom	Rev Cym2
0	65	ConGrndK	BrConGrK			Old EP	OldEP Tn		PierceCl			SmalOrgl						70sDrOr2	WarmJzOr	SloRotar	TrmOrgFl				TightAcd	EsGtrHrd	NashvllR	SuperJzB	MidT.Gtr	WrenchHv	ManhttnB	Bite Res	GtFeedbk	BostnBrt	Mod.Bass	HrdPikRs	PwrFrtlR	Thum&Slp		Sqr.Bass	AtkPulse	CadenzDk	Vla Sec	Hrd Vcs	Hrd CBs	Fear Dtd				SprStrSt	Strings3	Syn Str5	Virgo	Male Aah	Hmn	Aspirate	BrssStab	DrkTpSft	MellowTb	Slw Tuba	Bkstairs	HornOrc2	SprBrCut	SynthThn	Soft Cut	MdtatnRs	FakeAlto	SprTenor		HeinzUni					Boehm Br	Home	Meadow					SoloSine	Dunce	PureLead	HardSync	WireLead	Br.Layer		Soft Wrl	Libra	RotarStr	ClickPad	Lite Pad	GlassPad	Pan Pad	ChoursPd	Sweepy	AfrcnWnd	Rave	SftCryst	Harp Vox	ShinStar	Creeper	Big Pan	Odin														Real Tom	ElecPerc	RevCym3
0	66	DblConGr	MIDIGrd3			Tribecca	Flips		ClrClavi									CheezOrg	ClikOrgn	FstRotar					TghtAcdD	EsGtMllo	Nashvl12	SuperJzD	MidTGtSt	WrnchDbl	ManhttnD	Bite Dtd	GtrHrmo2	Coolth	Chase	PkBass +	TalkinBa	GltzySlp		RubberBa	CS Light	Vln Sec	Hrd Vla	Slw Vcs	Slw CBs	Apoclyps				Triste		Solitude	Platinum	Scroll	WrlChoir	AsprateD	DoublHit	Soft Trp	JJJ	Euphon		Brt Horn	SprBrBlw	SyncBrss	AnaHornS		FakeAlt+	SprTnr +		Oboe Exp					Pastoral							SineLead	BrassSaw	ElPrimtv		SynPluck	Cypher 1		Cant	Bell Pad	LightPad	Ana. Pad	Itopia	SqrTwang	Queever		Celstial	Carib	Fairy	LoudGlok	AtmosPad	BritStab	Ring Pad	SynPiano															Rock Tom	Syn Perc
0	67	MIDIGrd1	MIDIGrd4			Diploid1	FlipsDtd		SwpClavi									DrawOrg3	Grace	GlaclRtr						EsGtrDcy	OldSmple	SuperJzR	NasalGtr	Tin	ManhttnP	Bite +	Shimla	Coolth B	ChaseRes	PickBa4	NoizFrtl	FM Slap		Fish	MetlBass	Hrd Vlns	Slw Vlas			Brt Trem				Basso		Fate	OctavPWM	Scroll +	Ooh St	Facula	BrStab80	Blow	BrllntTb			Hrd Horn	Pwrd Sfz	SyncBrSt			FakeAltD	SprTnrSt							Shepherd							Pulse Ld	SawRiver			The Sync	Cypher 2		Mogul			SquarPad	CC Pad	SquarPd8			Monsoon		Hermit	ChrstBel	Planet		Ritual	Creation															Tim'sSet
0	68	MIDIGrd2	OldPiano			Flops	Flicks		SynClavi									StdiumOr	CrnGrace									DX JzGtr	NaslGtSt	GrooveMt		Burnout			BlueBass			FMSlpDtd		HardReso	FrcOscBa	Slw Vlns								Stacc H		Thulium	Taurus	Aah St			Bass Hit	Blow Dbl	Hrd Tb				PwrSfzBr	AnaHorn1				Tnr&Alto														SyncLead	BrPulsDb				Cypher 3		Distance			Snow Pad	CosmicPd				Io			VibeBell	Lyra		ToHeaven	StarDust
0	69	OldestAP				Soho	FliksDtd		SprClavi									StdiumO2	DimClick									DXJzGt D	Hammer M			Bombay			JazzyBa2					Wah Saw	Cubit									Stacc L		Brook	Frost	Aah Mix			BassHit+	4th TP	Brt BTb				Alto&Trp	AnaHorn2																		ForcdOsc	Saw Trp				SprCyphr		Sync B&L			Pixie	Aah Pad							DigiBell	Akasaka		MilkyWay	Reso&Pan
0	70					FlopsDtd	BrightDX		GtrClavi									GospelOr	Dusk									PulsJazz	Hammer B			Bombay S			FngBass3					Pluto	Cubit +									Hall Str		Brook St	Leo	Aah Orch			6th Hit	SynthTp	Hrd BTb				Tnr&Trp	AnHrnOct																		Accent	Hue						Ba Lead			Pisces	Ooh Pad							AirBells	DgBermda		Night	Ana Echo
0	71					Diploid2	BrtDXDtd		HardyPlk									ClkGsplO	FM Click									RghcastN	Hammer D			Jaipur								Pluto +	Keel									Str/FHrn		OldSynSt	SolPlexs				6thHit +	Sweet Tp					BrssBros	SawBrPwr																		Brick	StrghtSw									Spiral	Ooh Aah							BellHarp	Cloud Pd		Glisten
0	72					Brooklyn	Kitayama		HrdyPlk+									ChapelOr	Spoony									RghcastM	HammerSt											Stimuli	KeelPwrd									SolidStr			SunRise				Euro Hit	Mllw Swt					VagueBro																			Alum	StrtPuls									PolySPd2								Gamelmba	PulseKey		Puffy
0	73					Diploid3	Turnpik1		FMClavDb									DimChors	SprRotry										FMChoGtr											RunPulse	PlnPulse									SwellStr							EuroHit+	NormTps					BrssSec3																			Query	PWMania									PolyPdKg								Bounce	NoisePno		Mimicry
0	74					PhunkyDX	Turnpik2		RobotClv									Dawn	LoFiOrgn										FMChoGtS											TalkPuls	PwrdPuls									Str+Brss							Blowout	BrllntTp					SfrzdBr2																			FMSlwSwp	Mod Saw																	Ana Bell			Parasite
0	75					Nasal DX	Cerritos											Mellorgn	BeepOrgn										PeskyGtr											Node	PwrPulsB									3oct Str							Trcrtps	Fanfare					OctBrass																			SyncLdDb	Toad																				Cicada
0	76					NaslDXDt	Sunset											Fuzzorgn	Belief										ClaviGtr											Stainer	Pwrd Saw									5partStr													Alps																			Curse	FatOctav																				Beacon
0	77					Din	Soft DX											FMO	SnapOrgn																					StainAtk	SmoothBs																						Symphnc																			OctvBeep	Overdose																				GblnTalk
0	78					4 Way EP	Reso DX											70sDrOr3																						SweepSqr	SynAttck																						Phoenix																			Sine Ld2	PWMDecay																				Temple
0	79					Easy EP	PiercnDX											MoodOrgn																						SwpSqr +																																										SquarLd3	SawDecay
0	80					Sine EP	ShvrngDX																																	Stinks																																										SquarLd4	FatSawLd
0	81					Cheap EP	ShvrnDX+																																	StnksRes																																											DuckLead
0	82						RattlnDX																																	Reso Sqr																																											BoostSaw
0	83						RatlnDX+																																	Dagger																																											Mr.Saw
0	84						TinkerDX																																	Zinc																																											ThinSwLd
0	85						TinkrDX+																																	SweePWM																																											MouthSaw
0	86																																							SwPWM St																																											Dr.Lead2
0	87																																							Slow Wah																																											Saw Unis
0	88																																							Crook																																											OctSawLd
0	89																																							FstFltBa																																											Seq Saw1
0	90																																							Rubber30																																											Seq Saw2
0	91																																							FstResB2																																											SimplSaw
0	92																																							MinneaBs
0	93																																							Miami Bs
0	94																																							ResoTalk
0	96													Balafon		ChrchBel	Cimbalom									Ukulele	Mandolin	PdlSteel		Mu.DstGt				WalkSyBa			SynFretl			Hammer								Vln Harp							VoiceHmn			FluglHrn															BassClar	Bang Di	Qu Di		Kawala						Seq Ana.																			Smokey	BelChoir			Tambra	Rabab	Tsugaru	Taisho-k		Sheng	Er Hu	Pungi	Bonang	Atrigane	Tablas	Castanet	Gr.Cassa			RevSnar1
0	97													Balimba		Carillon	Santur										MndlnEns							Dim&Cool			SmthFrtl											VlnHrpDt										Cornet																																													Dharma			Tamboura	Gopichnt		Kanoon			Ban Hu	Hichriki	Altair		GlasPerc					RevSnar2
0	98													Log Drum			Yang Qin																																																																																										Oud		Zheng			Jing Hu	Suo Na	Gamelan		ThaiBell					RevKick1
0	99																																																																																																										Pi Pa							S.Gamlan							RevConBD
0	100																																																																																																																	Rama Cym							Rev Tom1
0	101																																																																																																																	AsianBel							Rev Tom2
0	126	GrandP #	BriteP #	El.Grand	HnkyTonk	EPiano1#	EPiano2#	Harpsi.	Clavi #	Celesta	Glocken	MusicBox	Vibes	Marimba	Xylophon	TubulBel	Dulcimer	DrawOrg#	PercOrg#	RockOrg#	ChrchOrg	ReedOrgn	Acordion	Harmnica	TangoAc#	NylonGt#	SteelGt#	JazzGtr#	CleanGtr	MuteGtr#	Ovrdriv#	DistGtr#	GtrHarmo	AcoBass#	FngrBa #	PickBass	Frtless#	SlapBa1#	SlapBa2#	SynBass1	SynBass2	Violin #	Viola	Cello	Contrabs	TremStr#	Pizz.Str	Harp	Timpani	Strngs1#	Strngs2#	Syn Str1	Syn Str2	ChoirAah	VoiceOoh	SynVoice	Orch.Hit	Trumpet#	Trmbone#	Tuba	MuteTrp#	Fr. Horn	BrssSec#	SynBrss1	SynBrss2	SprnoSax	AltoSax#	TenorSax	Bari.Sax	Oboe #	Eng.Horn	Bassoon	Clarinet	Piccolo	Flute #	Recorder	PanFlut#	Bottle	Shakhchi	Whistle	Ocarina	SquareLd	Saw Ld	CaliopLd	Chiff Ld	CharanLd	Voice Ld	Fifth Ld	Bass&Ld	NewAgePd	Warm Pad	PolySyPd	ChoirPad	BowedPad	MetalPad	Halo Pad	SweepPad	Rain	SoundTrk	Crystal	Atmosphr	Bright	Goblins	Echoes	Sci-Fi	Sitar	Banjo	Shamisen	Koto	Kalimba	Bagpipe	Fiddle	Shanai	TnklBell	Agogo	SteelDrm	Woodblok	TaikoDrm	MelodTom	Syn Drum	RevCymbl	FretNoiz	BrthNoiz	Seashore	Tweet	Telphone	Helicptr	Applause	Gunshot
0	127	GrandPno	BritePno	El.Grand	HnkyTonk	E.Piano1	E.Piano2	Harpsi.	Clavi	Celesta	Glocken	MusicBox	Vibes	Marimba	Xylophon	TubulBel	Dulcimer	DrawOrgn	PercOrgn	RockOrgn	ChrchOrg	ReedOrgn	Acordion	Harmnica	TangoAcd	NylonGtr	SteelGtr	Jazz Gtr	CleanGtr	Mute Gtr	Ovrdrive	Dist.Gtr	GtrHarmo	Aco.Bass	FngrBass	PickBass	Fretless	SlapBas1	SlapBas2	SynBass1	SynBass2	Violin	Viola	Cello	Contrabs	Trem.Str	Pizz.Str	Harp	Timpani	Strings1	Strings2	Syn Str1	Syn Str2	ChoirAah	VoiceOoh	SynVoice	Orch.Hit	Trumpet	Trombone	Tuba	Mute Trp	Fr. Horn	BrssSect	SynBrss1	SynBrss2	SprnoSax	Alto Sax	TenorSax	Bari.Sax	Oboe	Eng.Horn	Bassoon	Clarinet	Piccolo	Flute	Recorder	PanFlute	Bottle	Shakhchi	Whistle	Ocarina	SquareLd	Saw Ld	CaliopLd	Chiff Ld	CharanLd	Voice Ld	Fifth Ld	Bass&Ld	NewAgePd	Warm Pad	PolySyPd	ChoirPad	BowedPad	MetalPad	Halo Pad	SweepPad	Rain	SoundTrk	Crystal	Atmosphr	Bright	Goblins	Echoes	Sci-Fi	Sitar	Banjo	Shamisen	Koto	Kalimba	Bagpipe	Fiddle	Shanai	TnklBell	Agogo	SteelDrm	Woodblok	TaikoDrm	MelodTom	Syn Drum	RevCymbl	FretNoiz	BrthNoiz	Seashore	Tweet	Telphone	Helicptr	Applause	Gunshot
32	0	StGndPSt	GndPnoSt	BrghtGnd	60'sGrnd	StRichSt	RchGndSt	60'sJazz	StTghtSt	TghtGdSt	PowerGnd	MildGrnd	Timeworn	ChorusMn	Doom    	Phono   	Room    	AmbiGrnd	FlngGrnd	CelesGnd	Dbl Pno 	Montuno 	GrndDyno	David   	RhodyGnd	Perc Pno	GrandDX 	GrandDX2	Bob     	PianoStr	PnoStPad	SynStrPf	PianoPad	OctPf+Pd	Pf+Choir	ModPd Pf	Pia-Tron	SitaryPf	BrghtPno	Digital 	ChorDigi	Grnd+EP 	DigiGrnd	Grnd/wDX	ChoDigiP	GlassPno	DigiTine	CP      	CP-Symph	Trem CP	BrightCP	Digi CP1	Digi CP2	Jino    	Petit CP	Hnkytnk1	Hnkytnk2	Hnkytnk3	FMHkytnk	Tea     	Deodar  	70's EP 	80's EP 	Crisp EP	Sweetnes	Freeway 	Trem 70 	Remark  	Sample  	Mid 70's	Celest80	At Once 	TremDyno	TremWurl	Phase 70	DlydDyno	FlngDyno	Dstrtd70	Dyno 81 	Tonight 	Dyno 83 	Dbl 70's	Digi-Rho	Choir EP	Paddy EP	VcePd EP	Vibrt EP	60's EP 	Trump   	DonnyWrl	WurliAmp	Dg Wurli	FullTine	DX EP2  	DX 1980 	DX 1990 	Mllw DX 	ChrsTine	Chrs EP2	Chrs1980	Chrs1990	DarkDXEP	FTBallad	Sym EP2 	Chrs1982	90Ballad	816	DXEP+Pad	DXSynStr	DXEP+Cho	Balmy DX	GlassyEP	FM Piano	Chrs FMP	Harpsi 1	Harpsi 2	Harpsi 3	Harpsi 4	RichHpsi	ShrpHpsi	Clav 1  	Clav 2  	MuteClav	Phs Clav	PhsClav2	Wah Clav	DigiClav	Ch DgClv	PhsDgClv
48	0	MtdClavi	Orimba
48	8	Beeline	BlineHrd	Dwarf	Byte	Ping	NastyCut	NstyCtSt	Xe	OrganHit	OrgnHit+	Soft Hit	Vein	Packet	Jolly	Jolly +	Envy	EnvyShrt	Cough	Remark	Potala	Fury	Glocken+
48	16	Rage	TnglCaos	Incontnc	IncntClk	CheapOsc	CheapOc+	NstOrSpl	SprClick	Boomout	ChoirSpl	Veld	VaporVox	VoxShoot	SemiacOr
48	24	Fuss	VanAllen	Divinity	Paranoia	Vexation	CalcOrg1	CalcOrg2	CalcOrg3	ChoCalcO	Sodium
48	48	Reflex 1	Reflex 2	Prcesion	RndmWalk	RandmRun
48	56	Insanity	Habakkuk
48	64	DstnFire	BlowNoiz	Fall	Chaff
48	72	Litning	Oof	Lust	Lust St	SoftHit+	Cough +	Ruin	Ruin St	Vein +	Universe	UnvrsSwp	Xe +	Daze	Refusal	Refusal+	Lie	Malice	Doubt	DoubtDbl
48	80	Zipzap
48	88	Escape	Zigzag	Scud	Hinayana	Boot	Anathema	Germ 1	Germ 2	Malfnctn
48	96	TinKettl	K/S Anlg	K/S Humd	K/S Slap	Rvr/Crsh
48	104	Satya	Monastry	Vinaya	Prana	Delight	Puja	Bent Tom
48	120	Vodou
64	0	CuttngNz	CttngNz2	DstCutNz	Str Slap	B.Slide	P.Scrape											Fl.KClik																Shower	Thunder	Wind	Stream	Bubble	Feed	Cave										Dog	Horse	Tweet 2	Kitty	Growl	Haunted	Ghost	Maou	Insects	Bacteria							PhonCall	DoorSqek	DoorSlam	ScratchC	ScratchS	WindChim	Telphon2	AnthrScr	TurnTabl								CarEIgnt	CarTSqel	Car Pass	CarCrash	Siren	Train	JetPlane	Starship	Burst	Coaster	Submarin	Cnectvty	Mystery	Charging			Laugh	Scream	Punch	Heart	Footstep	Applaus2											MchinGun	LaserGun	Xplosion	Firework	Fireball
126	0	SFX Kit1	SFX Kit2															TknoKtKS	TknoKtHi	TknoKtKLo														SakuraKt	SLatinKit	ChinaKit																																																																														Kit01	Kit02	Kit03	Kit04
127	0	StndKit#	StndKit2	Dry Kit	BriteKit	Skim Kit	Slim Kit	RogueKit	Hob Kit	Room Kit	DarkRKit							Rock Kit	RockKit2							ElctrKit	AnalgKit	AnlgKit2	DanceKit	HipHpKit	JunglKit	ApogeeKt	PergeeKt	Jazz Kit	JazzKit2							BrushKit	BrshKit2							SymphKit								Ntrl Kit	NtFunkKt							TrampKit	AmberKit	CoffinKt
";
        static string drumMapTsv =
  @"
127	0														Surdo Mute	Surdo Open	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap	Brush Swirl	Brush Slap	BrushTapSwrl	Snare Roll	Castanet	Snare Soft	Sticks	Kick Soft	OpenRimShot	Kick Tight	Kick	Side Stick	Snare	Hand Clap	Snare Tight	Floor Tom L	Hi-HatClosed	Floor Tom H	Hi-Hat Pedal	Low Tom	Hi-Hat Open	Mid Tom L	Mid Tom H	CrashCymbal1	High Tom	RideCymbal 1	Chinese Cym	Ride Cym Cup	Tambourine	SplashCymbal	Cowbell	CrashCymbal2	Vibraslap	RideCymbal 2	Bongo H	Bongo L	Conga H Mute	Conga H Open	Conga L	Timbale H	Timbale L	Agogo H	Agogo L	Cabasa	Maracas	SambaWhistlH	SambaWhistlL	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	1														Surdo Mute	Surdo Open	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap	Brush Swirl	Brush Slap	BrushTapSwirl	Snare Roll 2	Castanet	Snare Soft 2	Sticks	Kick Soft	RimShotHShrt	KickTghtShrt	Kick Short	Side Stick	Snare Short	Hand Clap	SnareTight H	Floor Tom L	Hi-HatClosed	Floor Tom H	Hi-Hat Pedal	Low Tom	Hi-Hat Open	Mid Tom L	Mid Tom H	CrashCymbal1	High Tom	RideCymbal 1	Chinese Cym	Ride Cym Cup	Tambourine	SplashCymbal	Cowbell	Crash Cymbal 2	Vibraslap	RideCymbal 2	Bongo H	Bongo L	Conga H Mute	Conga H Open	Conga L	Timbale H	Timbale L	Agogo H	Agogo L	Cabasa	Maracas	SambaWhistlH	SambaWhistlL	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	2														Surdo MuteV	Surdo Open V	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap V	BrushSwirl V	Brush Slap V	BrushSwirlV	Snare Roll V	Castanet	SnareDrySoft	Sticks	KickDry Soft	RimShotDry V	KickDryTight	KickDry Mute	SideStickDry	Snare Dry	Hand Clap	SnareDryMute	FloorTmLShrt	Hi-HatClosed	FloorTmHShrt	Hi-Hat Pedal	LowTom Short	Hi-Hat Open	MidTomLShort	MidTomHShort	CrashCym 1 V	HighTomShort	RideCymbal1V	ChineseCym V	Ride Cym Cup	Tambourine	Splash Cym V	Cowbell	CrashCym 2 V	Vibraslap	RideCymbal2V	Bongo H V	Bongo L V	CongaHMute V	Conga H Open	Conga L V	Timbale H V	Timbale L V	Agogo H V	Agogo L V	Cabasa	Maracas	SambaWhislHV	SambaWhislLV	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute V	Cuica Open V	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	3														Surdo MuteB	Surdo Open B	Hi Q B	Whip Slap B	Scratch H B	Scratch L B	FingerSnap B	ClickNoiseB	MtrnmClick B	Mtrnm BellB	SeqClick L B	SeqClick H B	Brush Tap B	BrshSwirl B	Brush Slap B	BrshTapSwrlB	Snare Roll B	Castanet B	Snare Soft B	Sticks B	Kick Soft B	OpenRimShotB	Kick Tight B	Kick B	Side Stick B	Snare B	Hand Clap B	SnareTight B	FloorTom L B	HiHatCloseLB	FloorTom H B	HiHatPedal B	Low Tom B	HiHat Open B	Mid Tom L B	Mid Tom H B	CrashCym 1 B	High Tom B	RideCymbal1B	ChineseCym B	RideCupShort	Tambourine B	Splash Cym B	Cowbell L	CrashCym 2 B	Vibraslap B	RideCymbal2B	Bongo H B	Bongo L B	CongaHMute B	CongaHOpen B	Conga L B	Timbale H B	Timbale L B	Agogo H B	Agogo L B	Cabasa B	Maracas B	SambaWhstlHB	SambaWhstlLB	GuiroShort B	Guiro Long B	Claves B	WoodBlockH B	WoodBlockL B	Cuica Mute B	Cuica Open B	TriangleMuteB	TriangleOpenB	Shaker B	JingleBellsB	Bell Tree B
127	4														Surdo MuteV	Surdo Open V	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap V	BrushSwirl V	Brush Slap V	BrshTapSwrlL	Snare Roll V	Castanet Sk	Snare Dry Q	Sticks	KckDrySftHPF	Rim Dry HPF	KckDryTght Q	KckDryMu HPF	SdStck Dry Q	Snare Dry H	Hand Clap Sk	Snr Dry Mu Q	FlrTmLShrtSk	Hat Closed H	FlrTmHShrtSk	Hat Pedal H	LowTomShrtSk	Hi-HatOpen H	MidTmLShrtSk	MidTmHShrtSk	CrashCym 1 Q	HighTmShrtSk	RideCym1 Sk	Chinese HPF	Ride Cup Q	Tambourine Q	Splash Cym H	Cowbell HPF	CrashCym 2 D	Vibraslap	RideCymbal2Q	Bongo H HPF	Bongo L HPF	CongaHMu HPF	CongaHOpnHPF	Conga L HPF	TimbaleH HPF	TimbaleL HPF	Agogo H HPF	Agogo L HPF	Cabasa BPF	Maracas L	WhistlH BPF	WhistlL BPF	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open H	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	5														Surdo MuteV	Surdo Open V	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap V	BrushSwirl V	Brush Slap V	BrshTapSwrlL	Snare Roll V	Castanet H	SnareRough Q	Sticks Q	KickSoftDark	OpenRim Sl	KckTghtShrtL	Kick Short D	Side Stick Q	Snr Shrt HPF	Hand Clap D	Snr Tght Mu	FlrTomL Tght	HiHatCloseLQ	FlrTomH Tght	HiHatPedal Q	LowTom Tight	HiHat Open Q	MidTomL Tght	MidTomH Tght	CrashCym 1 L	HighTom Tght	RideCymbal1L	ChineseCym L	RideCymCup L	Tambourine	SplashLShort	Cowbell Dark	CrashCym 2 L	Vibraslap	RideCymbal2L	Bongo H V	Bongo L V	CongaHMute V	CongaHOpen V	Conga L H	Timbale H V	Timbale L V	Agogo H V	Agogo L V	Cabasa	Maracas Q	SambaWhislHV	SambaWhislLV	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open H	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	6														Surdo MuteV	Surdo Open V	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap V	BrushSwirl V	Brush Slap V	BrshTapSwrlL	Snare Roll V	Castanet H	Snr Brss Sft	Sticks	Kick Soft 2	OpenRimShot2	Kick Dark 2	Kick Tight 4	SdStick Tght	SnrSnppyShrt	Hand Clap	Snr Brss Hrd	FloorTmLTght	HiHatClose 3	FloorTmHTght	HiHatPedal 3	LowTom Tight	HiHat Open 3	MidTomLTight	MidTomHTight	CrashCymbal3	HighTomTight	RideCymbal 3	ChineseCym 2	RideCymCup 2	Tambourine	Splash Cym V	Cowbell Mid	CrashCymbal4	Vibraslap	RideCymbal4Q	Bongo H V	Bongo L V	CongaHMute 2	CongaHOpen 2	Conga L 2	Timbale H V	Timbale L V	Agogo H V	Agogo L V	Cabasa	Maracas Q	SambaWhislHV	SambaWhislLV	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open H	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	7														Surdo MuteV	Surdo Open V	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap V	BrushSwirl V	Brush Slap V	BrshTapSwrlV	Snare Roll V	Castanet H	SnrBrssSft H	Sticks	Kick Soft2 H	Rim H Shrt 2	KickDark 2 H	KickTight4 H	SdStickightH	Snppy Shrt H	Hand Clap	SnrBrssHrd H	FlrTmLTght H	HiHatClose3H	FlrTmHTght H	HiHatPedal3H	LowTomTghtH	HiHatOpen3 H	MidTomLTghtH	MidTomHTghtH	CrashCym 3 H	HighTomTghtH	RideCymbal3H	ChineseCym2H	RideCymCup2H	Tambourine H	Splash Cym H	Cowbell H	CrashCym 4 H	Vibraslap	RideCymbal 4	Bongo H V	Bongo L V	CongaHMute2H	CongaHOpen2H	Conga L 2 H	Timbale H V	Timbale L V	Agogo H V	Agogo L V	Cabasa	Maracas Q	SambaWhislHV	SambaWhislLV	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open H	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	8														Surdo Mute	Surdo Open	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap	Brush Swirl	Brush Slap	BrushTapSwrl	Snare Roll	Castanet	Snare Soft	Sticks	Kick Soft	OpenRimShot	Kick Tight	Kick Room	Side Stick	Snare Snappy	Hand Clap	SnrTightSnpy	Tom Room 1	Hi-HatClosed	Tom Room 2	Hi-Hat Pedal	Tom Room 3	Hi-Hat Open	Tom Room 4	Tom Room 5	CrashCymbal1	Tom Room 6	RideCymbal 1	Chinese Cym	Ride Cym Cup	Tambourine	SplashCymbal	Cowbell	CrashCymbal2	Vibraslap	RideCymbal 2	Bongo H	Bongo L	Conga H Mute	Conga H Open	Conga L	Timbale H	Timbale L	Agogo H	Agogo L	Cabasa	Maracas	SambaWhistlH	SambaWhistlL	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	9														Surdo MuteV	Surdo Open V	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap V	BrushSwirl V	Brush Slap V	BrshTapSwrlV	Snare Roll V	Castanet	Snare Soft	Sticks	Kick Soft	OpenRimShot	Kick Dark	KickRoomGate	Side Stick	SnareSnappy2	Hand Clap	SnrTghtSnpy2	Tom Room 1 Q	HiHatClose Q	Tom Room 2 Q	HiHatPedal Q	Tom Room 3 Q	HiHat Open L	Tom Room 4 D	TomRoom5 L D	CrashCymbal1	TomRoom6 L D	RideCymbal1V	ChineseCym V	Ride Cym Cup	Tambourine	Splash Cym V	Cowbell	CrashCym 2 V	Vibraslap	RideCymbal2V	Bongo H V	Bongo L V	CongaHMute V	Conga H Open	Conga L V	Timbale H V	Timbale L V	Agogo H V	Agogo L V	Cabasa	Maracas	SambaWhislHV	SambaWhislLV	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute V	Cuica Open V	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	16														Surdo Mute	Surdo Open	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap	Brush Swirl	Brush Slap	BrushTapSwrl	Snare Roll	Castanet	Snare Noisy	Sticks	Kick Tight 2	OpenRimShot	Kick 2	Kick Gate	Side Stick	Snare Rock	Hand Clap	SnareRockRim	Tom Rock 1	Hi-HatClosed	Tom Rock 2	Hi-Hat Pedal	Tom Rock 3	Hi-Hat Open	Tom Rock 4	Tom Rock 5	CrashCymbal1	Tom Rock 6	RideCymbal 1	Chinese Cym	Ride Cym Cup	Tambourine	SplashCymbal	Cowbell	CrashCymbal2	Vibraslap	RideCymbal 2	Bongo H	Bongo L	Conga H Mute	Conga H Open	Conga L	Timbale H	Timbale L	Agogo H	Agogo L	Cabasa	Maracas	SambaWhistlH	SambaWhistlL	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	17														Surdo MuteV	Surdo Open V	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap V	BrushSwirl V	Brush Slap V	BrshTapSwrlV	Snare Roll V	Castanet	SnareNoisy 5	Sticks	Kick Tight 3	OpenRimShot	Kick 4	Kick Gate 2	Side Stick	Snare Rock 2	Hand Clap	SnrRockRim Q	Tom Rock 1 H	HiHatClose 2	Tom Rock 2 H	HiHatPedal 2	TomRck3LShrt	HiHat Open 2	TomRck4LShrt	TomRck5LShrt	CrashCymbal1	TomRck6LShrt	RideCymbal1V	ChineseCym V	Ride Cym Cup	Tambourine	Splash Cym V	Cowbell	CrashCym 2 V	Vibraslap	RideCymbal2V	Bongo H V	Bongo L V	CongaHMute V	Conga H Open	Conga L V	Timbale H V	Timbale L V	Agogo H V	Agogo L V	Cabasa	Maracas	SambaWhislHV	SambaWhislLV	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute V	Cuica Open V	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	24														Surdo Mute	Surdo Open	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap	Brush Swirl	Brush Slap	ReversCymbal	Snare Roll	Hi Q 2	SnrSnpyElctr	Sticks	Kick 3	OpenRimShot	Kick Gate	KckGateHeavy	Side Stick	SnareNoisy 2	Hand Clap	SnareNoisy 3	TomElectro 1	Hi-HatClosed	TomElectro 2	Hi-Hat Pedal	TomElectro 3	Hi-Hat Open	TomElectro 4	TomElectro 5	CrashCymbal1	TomElectro 6	RideCymbal 1	Chinese Cym	Ride Cym Cup	Tambourine	SplashCymbal	Cowbell	CrashCymbal2	Vibraslap	RideCymbal 2	Bongo H	Bongo L	Conga H Mute	Conga H Open	Conga L	Timbale H	Timbale L	Agogo H	Agogo L	Cabasa	Maracas	SambaWhistlH	SambaWhistlL	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Scratch H 2	Scratch L 2	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	25														Surdo Mute	Surdo Open	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap	Brush Swirl	Brush Slap	ReversCymbal	Snare Roll	Hi Q 2	SnareNoisy 4	Sticks	Kick Tight 2	OpenRimShot	KickAnlgShrt	Kick Analog	SideStickAn	SnareAnalog	Hand Clap	SnareAnalog2	Tom Analog 1	HatCloseAnlg	Tom Analog 2	HatCloseAn 2	Tom Analog 3	HatOpen Anlg	Tom Analog 4	Tom Analog 5	Crash Analog	Tom Analog 6	RideCymbal 1	Chinese Cym	Ride Cym Cup	Tambourine	SplashCymbal	Cowbell Anlg	CrashCymbal2	Vibraslap	RideCymbal 2	Bongo H	Bongo L	Conga Anlg H	Conga Anlg M	Conga Anlg L	Timbale H	Timbale L	Agogo H	Agogo L	Cabasa	Maracas 2	SambaWhistlH	SambaWhistlL	Guiro Short	Guiro Long	Claves 2	Wood Block H	Wood Block L	Scratch H 2	Scratch L 3	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	26														Surdo MuteV	Surdo Open V	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap V	BrushSwirl V	Brush Slap V	ReversCymbal	Snare Roll V	Hi Q 2	SnareAnalog3	Sticks	KckTeknoSoft	RimShotDry V	KckTeknoTght	Kick Techno	SideStickAn	Snare Techno	Hand Clap	SnareTechno2	Tom Analog 1	HatCloseAnlg	Tom Analog 2	HatCloseAn 2	Tom Analog 3	HatOpen Anlg	Tom Analog 4	Tom Analog 5	Crash Analog	Tom Analog 6	RideCymbal1V	ChineseCym V	Ride Cym Cup	Tambourine	Splash Cym V	Cowbell Anlg	CrashCym 2 V	Vibraslap	RideCymbal2V	Bongo H V	Bongo L V	Conga Anlg H	Conga Anlg M	Conga Anlg L	Timbale H V	Timbale L V	Agogo H V	Agogo L V	Cabasa	Maracas 2	SambaWhislHV	SambaWhislLV	Guiro Short	Guiro Long	Claves 2	Wood Block H	Wood Block L	Scratch H 2	Scratch L 3	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	27														Surdo Mute	Surdo Open	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap	Brush Swirl	Brush Slap	ReversCymbal	Snare Roll	Hi Q 2	SnareTechno3	Sticks	KickTechno Q	Rim Gate	KickTechno L	KickTechno 2	SideStickAn	Snare Clap	Hand Clap	Snare Dry 2	Tom Analog 1	HiHatClose 3	Tom Analog 2	HatCloseAn 2	Tom Analog 3	HiHat Open 3	Tom Analog 4	Tom Analog 5	Crash Analog	Tom Analog 6	RideCymbal 1	Chinese Cym	Ride Cym Cup	Tambourine	SplashCymbal	Cowbell Anlg	CrashCymbal2	Vibraslap	RideCymbal 2	Bongo H	Bongo L	Conga Anlg H	Conga Anlg M	Conga Anlg L	Timbale H	Timbale L	Agogo H	Agogo L	Cabasa	Maracas 2	SambaWhistlH	SambaWhistlL	Guiro Short	Guiro Long	Claves 2	Wood Block H	Wood Block L	Scratch H 2	Scratch L 3	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	28														Surdo MuteV	Surdo Open V	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap V	BrushSwirl V	Brush Slap V	BrshTapSwrlV	Snare Roll V	Castanet	RimShot2Soft	Sticks	KickDrySoft2	OpenRimShot2	Kick Dim	Kick Boon	SideStickDry	SnareDrySoft	Hand Clap	Snare White	FloorTmLShrt	HiHatClose2H	FloorTmHShrt	HiHatPedal2H	LowTom Short	HiHatOpen2 L	MidTomLShort	MidTomHShort	CrashCym 1 V	HighTomShort	RideCymbal1V	ChineseCym V	Ride Cym Cup	Tambourine	Splash Cym V	Cowbell	Crash Cym 2 V	Vibraslap	RideCymbal2V	Bongo H V	Bongo L V	CongaHMute V	Conga H Open	Conga L V	Timbale H V	Timbale L V	Agogo H V	Agogo L V	Cabasa	Maracas	SambaWhislHV	SambaWhislLV	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute V	Cuica Open V	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	29														Surdo MuteV	Surdo Open V	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap V	BrushSwirl V	Brush Slap V	BrshTapSwrlV	Snare Roll V	Castanet	Rim Gate 2	Sticks	Kick Cough	Rim Gate 3	Kick Zap	Kick Dawn	SideStickDry	Snare Tin	Hand Clap	Snare Can	FloorTmLShrt	HiHatClose2S	FloorTmHShrt	HiHatPedal2S	LowTom Short	HiHatOpen2 S	MidTomLShort	MidTomHShort	CrashCym 1 V	HighTomShort	RideCymbal1V	ChineseCym V	Ride Cym Cup	Tambourine	Splash Cym V	Cowbell	CrashCym 2 V	Vibraslap	RideCymbal2V	Bongo H V	Bongo L V	CongaHMute V	Conga H Open	Conga L V	Timbale H V	Timbale L V	Agogo H V	Agogo L V	Cabasa	Maracas	SambaWhislHV	SambaWhislLV	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute V	Cuica Open V	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	30														Surdo MuteV	Surdo Open V	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap V	BrushSwirl V	Brush Slap V	ReversCymbal	Snare Roll	Hi Q 2	SnareAnalog4	Sticks	KickTechno 3	OpenRimShotL	KickTechno 4	KckTknoTght 2	SideStickAn2	SnareAnalog5	ClapAmbience	SnareAnalog6	Tom Techno 1	HatCloseAn 3	Tom Techno 2	HatCloseAn 4	Tom Techno 3	HatOpenAn 2	Tom Techno 4	Tom Techno 5	Crash Analog	Tom Techno 6	RideAnalog 1	Chinese Cym	RideCymCup Q	Tambourine	Splash Cym V	CowbellAnlgL	CrashCym 2 V	Vibraslap	RideAnalog 2	Bongo H V	Bongo L V	CongaAnH Lng	CongaAnM Lng	CongaAnL Lng	Timbale H V	Timbale L V	Agogo H V	Agogo L V	Cabasa	Maracas 2	SambaWhislHV	SambaWhislLV	Guiro Short	Guiro Long	Claves 2	Wood Block H	Wood Block L	Scratch H 2	Scratch L 3	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	31														Surdo MuteV	Surdo Open V	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap V	BrushSwirl V	Brush Slap V	ReversCymbal	Snare Roll	Hi Q 2	Snare An 4 H	Sticks	KickTechno 3	OpenRimShotL	KickTechno4H	KckTknTght2H	SideStckAn2H	Snare An 5 H	Clap Amb H	Snare An 6 H	TomTechno1 H	HatCloseAn3H	TomTechno2 H	HatCloseAn4H	TomTechno3 H	HatOpenAn2 H	TomTechno4 H	TomTechno5 H	CrashAnalogH	TomTechno6 H	RideAnalog1H	ChineseCym H	RideCymCup H	Tambourine H	Splash Cym H	CowbellAnlgH	CrashCym 2 H	Vibraslap	RideAnalog2H	Bongo H V	Bongo L V	CongaAnHLngH	CongaAnMLngH	CongaAnLLngH	Timbale H V	Timbale L V	Agogo H V	Agogo L V	Cabasa	Maracas 2	SambaWhislHV	SambaWhislLV	Guiro Short	Guiro Long	Claves 2	Wood Block H	Wood Block L	Scratch H 2	Scratch L 3	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	32														Surdo Mute	Surdo Open	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap	Brush Swirl	Brush Slap	BrushTapSwrl	Snare Roll	Castanet	Snare Soft	Sticks	Kick Soft	OpenRimShot	Kick Tight	Kick Jazz	Side Stick	Snare	Hand Clap	Snare Tight	Tom Jazz 1	Hi-HatClosed	Tom Jazz 2	Hi-Hat Pedal	Tom Jazz 3	Hi-Hat Open	Tom Jazz 4	Tom Jazz 5	CrashCymbal1	Tom Jazz 6	RideCymbal 1	Chinese Cym	Ride Cym Cup	Tambourine	SplashCymbal	Cowbell	CrashCymbal2	Vibraslap	RideCymbal 2	Bongo H	Bongo L	Conga H Mute	Conga H Open	Conga L	Timbale H	Timbale L	Agogo H	Agogo L	Cabasa	Maracas	SambaWhistlH	SambaWhistlL	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	33														Surdo MuteV	Surdo Open V	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap V	BrushSwirl V	Brush Slap V	BrshTapSwrlV	Snare Roll V	Castanet	Snare Soft	Sticks	Kick Soft	OpenRimShot	Kick Tight	Kick Jazz L	Side Stick	Snare H	Hand Clap	SnareTight L	Tom Jazz 7	HiHatClosed L	Tom Jazz 8	HiHat Pedal L	Tom Jazz 9	HiHat Open L	Tom Jazz 10	Tom Jazz 11	CrashCymbal1	Tom Jazz 12	RideCymbal1V	ChineseCym V	RideCymCup L	Tambourine	Splash Cym V	Cowbell	CrashCym 2 V	Vibraslap	RideCymbal2V	Bongo H V	Bongo L V	CongaHMute V	Conga H Open	Conga L V	Timbale H V	Timbale L V	Agogo H V	Agogo L V	Cabasa	Maracas	SambaWhislHV	SambaWhislLV	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute V	Cuica Open V	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	40														Surdo Mute	Surdo Open	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap	Brush Swirl	Brush Slap	BrushTapSwrl	Snare Roll	Castanet	Blash Slap 2	Sticks	Kick Soft	OpenRimShot	Kick Tight	Kick Small	Side Stick	Brush Slap 3	Hand Clap	Brush Tap 2	Tom Brush 1	Hi-HatClosed	Tom Brush 2	Hi-Hat Pedal	Tom Brush 3	Hi-Hat Open	Tom Brush 4	Tom Brush 5	CrashCymbal1	Tom Brush 6	RideCymbal 1	Chinese Cym	Ride Cym Cup	Tambourine	SplashCymbal	Cowbell	CrashCymbal2	Vibraslap	RideCymbal 2	Bongo H	Bongo L	Conga H Mute	Conga H Open	Conga L	Timbale H	Timbale L	Agogo H	Agogo L	Cabasa	Maracas	SambaWhistlH	SambaWhistlL	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	41														Surdo Mute	Surdo Open	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap	Brush Swirl	Brush Slap	BrshTapSwrlL	Snare Roll V	Castanet H	SnareDryHrd	Sticks	KickRelease	RimShtDry L	KickCloudy H	KickCloudy L	SideStick B2	BrushSlap3 Q	Hand Clap	BrshSnrLoud	Tom Brush 7	HiHatClose 4	Tom Brush 8	HiHatPedal 4	Tom Brush 9	HiHat Open 4	Tom Brush 10	Tom Brush 11	CrashCym 4	Tom Brush 12	RideCymbal1H	Chinese Cym	RideCymCup 6	Tambourine	Splash Cym V	Cowbell 2	CrashCymbal2	Vibraslap	RideCymbal 6	Bongo H	Bongo L	CongaHMute V	Conga H Open	Conga L 2	Timbale H	Timbale L	Agogo H	Agogo L	Cabasa	Maracas Q	SambaWhistlH	SambaWhistlL	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open H	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	48														Surdo Mute	Surdo Open	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap	Brush Swirl	Brush Slap	BrushTapSwil	Snare Roll	Castanet	Brush Slap 2	Sticks	Kick Soft 2	OpenRimShot	Gran Cassa	GranCassa Mu	Side Stick	Band Snare	Hand Clap	Band Snare 2	Tom Jazz 1	Hi-HatClosed	Tom Jazz  2	Hi-Hat Pedal	Tom Jazz  3	Hi-Hat Open	Tom Jazz  4	Tom Jazz  5	Hand Cymbal	Tom Jazz  6	HandCymShort	Chinese Cym	Ride Cym Cup	Tambourine	SplashCymbal	Cowbell	HandCymbal 2	Vibraslap	HandCym2Shrt	Bongo H	Bongo L	Conga H Mute	Conga H Open	Conga L	Timbale H	Timbale L	Agogo H	Agogo L	Cabasa	Maracas	SambaWhistlH	SambaWhistlL	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	56														Surdo Mute	Surdo Open	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap Nt	BrshSwrlNt L	BrushSlap Nt	BrshSwrlNt H	SnareRoll Nt	Castanet	Snare Nt L	Sticks	Kick Soft Nt	Open Rim Nt	KickLight Nt	Kick Std Nt	SideStick Nt	Snare Nt M	Hand Clap	Snare Nt H	FloorTomNt L	HiHatCloseNt	FloorTomNt H	HiHatPedalNt	Low Tom Nt	HiHatOpenNt	Mid Tom Nt L	Mid Tom Nt H	CrashCymNt 1	High Tom Nt	RideCym Nt 1	ChineseCymNt	RideCymCupNt	Tambourine	SplashCym Nt	Cowbell	CrashCymNt 2	Vibraslap	RideCym Nt 2	Bongo H	Bongo L	Conga H Mute	Conga H Open	Conga L	Timbale H	Timbale L	Agogo H	Agogo L	Cabasa	Maracas	SambaWhistlH	SambaWhistlL	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	57														Surdo Mute	Surdo Open	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap Nt	BrshSwrlNt L	BrushSlap Nt	BrshSwrlNt H	SnareRoll Nt	Castanet	Snare NtF L	Sticks	Kick Soft Nt	Open Rim Nt	Kick Std NtF	Kick NtF	SideStick Nt	Snare NtF M	Hand Clap	Snare NtF H	FloorTomNt L	HiHatCloseNt	FloorTomNt H	HiHatPedalNt	Low Tom Nt	HiHatOpenNt	Mid Tom Nt L	Mid Tom Nt H	CrashCymNt 1	High Tom Nt	RideCym Nt 1	ChineseCymNt	RideCymCupNt	Tambourine	SplashCym Nt	Cowbell	CrashCymNt 2	Vibraslap	RideCym Nt 2	Bongo H	Bongo L	Conga H Mute	Conga H Open	Conga L	Timbale H	Timbale L	Agogo H	Agogo L	Cabasa	Maracas	SambaWhistlH	SambaWhistlL	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	64														Surdo Mute	Surdo Open	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap V	BrushSwirl V	Brush Slap V	ReversCymbal	Snare Roll V	Hi Q 2	SnrTechno3 Q	Sticks Q	KickTechnoQ2	RimGate LoFi	KickTechnoLQ	KckTkno2Gate	SideStckAn Q	Snare Clap	Hand Clap D	SnrDry2 Gate	Tom Analog 7	HiHatClose3D	Tom Analog 8	HatCloseAn2L	Tom Analog 9	HiHatOpen3 D	TomAnalog 10	TomAnalog 11	CrashAnalogD	TomAnalog 12	RideCymbal1D	ChineseCym L	RideCymCup D	Tambourine D	SplashCymL Q	CowbellAnlgQ	CrashCym 2 Q	Vibraslap	RideCymbal2D	Bongo H V	Bongo L V	CongaAnH Lng	CongaAnM Lng	CongaAnL Lng	Timbale H V	Timbale L V	Agogo H V	Agogo L V	Cabasa	Maracas 2	SambaWhislHV	SambaWhislLV	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Scratch H 2	Scratch L 3	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	65														Surdo MuteV	Surdo Open V	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap V	BrushSwirl V	Brush Slap V	BrshTapSwrlL	Snare Roll V	Castanet	RimShot3Soft	Sticks Q	KickDrySoft3	OpnRimShtDry	KickComp 1 L	KickComp 1 H	SdStickDry L	SnrDryMute L	Hand Clap D	HipSnrLong	FlrTmTech L	HatCloseTech	FlrTmTech H	Hat Pdl Tech	Low Tom Tech	HiHatOpen3 D	MidTomTech L	MidTomTech H	CrashCymbalD	Hi Tom Tech	RideCymbal1D	ChineseCymH2	RideCymCup D	Tambourine D	SplashCymL Q	CowbellLo-Fi	CrashCym 2 Q	Vibraslap	RideCymbal2V	Bongo H V	Bongo L V	CongaHMute V	Conga H Open	Conga L 2	Timbale H V	Timbale L V	Agogo H V	Agogo L V	Cabasa	Maracas Q	SambaWhislHV	SambaWhislLV	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open H	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	66														Surdo MuteV	Surdo Open V	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap V	BrushSwirl V	Brush Slap V	BrshTapSwrlL	Snare Roll V	Castanet	Rim Gate 4	Sticks Q	Kick Cough L	Rim Gate 5	KickComp 2 L	KickComp 2 H	SdStickDry L	Snare Tin L	Hand Clap D	Snare Can L	FlrTmTech L	HatCloseTech	FlrTmTech H	Hat Pdl Tech	Low Tom Tech	HiHatOpen3 D	MidTomTech L	MidTomTech H	Crash Cym D2	Hi Tom Tech	RidCymblHrd2	ChineseCymQ	RideCymCup 5	Tambourine D	JnglSplsjCym	CowbellLo-Fi	CrashCym 2 Q	Vibraslap	RideCymbal 5	Bongo H V	Bongo L V	CongaHMute V	Conga H Open	Conga L 2	Timbale H V	Timbale L V	Agogo H V	Agogo L V	Cabasa	Maracas Q	SambaWhislHV	SambaWhislLV	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open H	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	126														Surdo Mute	Surdo Open	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap	Brush Swirl	Brush Slap	BrushTapSwrl	Snare Roll	Castanet #	Snare Soft #	Sticks	Kick Soft	OpenRim #	Kick Tight	Kick	Side Stick #	Snare #	Hand Clap	Snare Tight#	Floor Tom L	Hi-HatClosed#	Floor Tom H	Hi-Hat Pedal#	Low Tom	Hi-Hat Open#	Mid Tom L	Mid Tom H	Crash Cym1 #	High Tom	RideCymbal1#	Chinese Cym#	Ride CymCup#	Tambourine	SplashCymbal	Cowbell #	CrashCym2 #	Vibraslap	RideCymbal2#	Bongo H	Bongo L	CongaHMute #	CongaHOpen #	Conga L #	Timbale H	Timbale L	Agogo H	Agogo L	Cabasa	Maracas	SambaWhistlH	SambaWhistlL	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
127	127														Surdo Mute	Surdo Open	Hi Q	Whip Slap	Scratch H	Scratch L	Finger Snap	Click Noise	Mtrnm Click	Mtrnm Bell	Seq Click L	Seq Click H	Brush Tap	Brush Swirl	Brush Slap	BrushTapSwrl	Snare Roll	Castanet	Snare Soft	Sticks	Kick Soft	OpenRimShot	Kick Tight	Kick	Side Stick	Snare	Hand Clap	Snare Tight	Floor Tom L	Hi-HatClosed	Floor Tom H	Hi-Hat Pedal	Low Tom	Hi-Hat Open	Mid Tom L	Mid Tom H	CrashCymbal1	High Tom	RideCymbal 1	Chinese Cym	Ride Cym Cup	Tambourine	SplashCymbal	Cowbell	CrashCymbal2	Vibraslap	RideCymbal2	Bongo H	Bongo L	Conga H Mute	Conga H Open	Conga L	Timbale H	Timbale L	Agogo H	Agogo L	Cabasa	Maracas	SambaWhistlH	SambaWhistlL	Guiro Short	Guiro Long	Claves	Wood Block H	Wood Block L	Cuica Mute	Cuica Open	TriangleMute	TriangleOpen	Shaker	Jingle Bells	Bell Tree
126	0																													Insects	Bacteria							CuttingNoiz	CuttingNoiz2	DstCuttingNz Noise	String Slap	Bass Slide	Pick Scrape											Fl.Key Click																Shower	Thunder	Wind	Stream	Bubble	Feed	Cave										Dog	Horse	Bird Tweet 2	Kitty	Growl	Haunted	Ghost	Maou
126	1																																					Phone Call	Door Squeak	Door Slam	Scratch Cut	Scratch H 3	Wind Chime	Telephone 2										CarEngnIgnit	CarTireSqueal	Car Passing	Car Crash	Siren	Train	Jet Plane	Starship	Burst	Coaster	Submarine	Connectivity	Mystery				Laugh	Scream	Punch	Heart Beat	Foot Steps	Applause 2											Machine Gun	Laser Gun	Explosion	Firework	Fireball
126	16																																					HvyTknoKick1	HvyTknoKick2	PsychdlcKick	GateTknoKick	Rap Kick	HvyTknoKick3	HvyTknoKick4	Future Kick	Asian Kick	ImblncKick	Justice Kick	Minimal Kick					Radio Snare	ColdDrySnr 1	Slap Snare	ColdDry Snr 2	ColdDry Snr 3	LoFiMtlSnare											HiPitchSlapH	HiPitchSlapL
126	17																																					Hyper Tom H 1	Asian Tom H	Lo-Fi Tom H	Hyper Tom H 2	FlangedTom H	MinimalTom H	Vox Drum H	AndroidWlk1H	AndroidWlk2H	ElectroBlipH	Wood Perc H	WoodDoorOpnH	ResNoizBrstH	LFOMtlAtck H	SteelConga H	RateDwnSnr H	Po Ambient H	TnnlAmbientH	Vibraslap H	GunShotSlapH	PunchSnareH	Bomb Snare H	SpcTmburineH	AmbntCowBellH	Chink Hat H	CoalMine 1 H	CoalMine 2 H	HammerHit1 H	HammerHit2 H	HammerHit3 H	InsnsblHah H	Robot 1 H	InsnsblFuh H	Robot 2 H	RudeLoopCym H	NoiseBurst H	Fizzer H	Lo-Fi ShakerH	TempleGong H
126	18																																					Hyper Tom L1	Asian Tom L	Lo-Fi Tom L	Hyper Tom L2	FlangedTom L	MinimalTom L	Vox Drum L	AndroidWlk1L	AndroidWlk2L	ElectroBlipL	Wood Perc L	WoodDoorOpnL	ResNoizBrstL	LFOMtlAtck L	SteelConga L	RateDwnSnr L	PopAmbient L	TnnlAmbientL	Vibraslap L	GunShotSlapL	PunchSnare L	Bomb Snare L	SpcTmburineL	AmbntCowBllL	Chink Hat L	CoalMine 1 L	CoalMine 2 L	HammerHit1 L	HammerHit2 L	HammerHit3 L	InsnsblHah L	Robot 1 L	InsnsblFuh L	Robot 2 L	RudeLoopCymL	NoiseBurst L	Fizzer L	Lo-FiShakerL	TempleGong L
126	32																																					Dora	Tsuzumi Pon	Tsuzumi Pu	Tsuzumi Ta	Tsuzumi Chon	Tsuzumi Tsu	ShimetaikoTen	ShimetaikoTsu	Yagura Open	Ohdaiko Rim	Orient Tmbrn	OrientDrum 1	OrientDrum 2	OrientDrum 3	Orient Rim 1	Orient Rim 2	Orient Rim 3	Orient Rim 4	Metal Rim 1	Metal Rim 2	Metal Rim 3	Metal Rim 4	Metal Rim 5
126	33																																					Ltn Cym Shrt	Claves SL 1	Claves SL 2	Claves SL 3	Claves SL 4	Claves SL 5	MtdPerc SL 1	MutPerc SL 2	MutPerc SL 3	MutPerc SL 4	Pandiero	SurdoMuteSL1	SurdoMuteSL2	SurdoOpen SL	Surdo Rim SL	TamborimMute	TamborimOpen	TimbaleLDrum	TimbaleHDrum	TimbaleL Rim	TimbaleH Rim	TimbalePaila1	TimbalePaila2
126	34																																					Bangu	Dagu Mute	Dagu Heavy	Paigu High	Paigu Middle	Paigu Low											ZhongchaMute	ZhongchaOpen	ZhongluoMute	ZhongluoOpen	XiaoluoOpen	XizochaMute	XiaochaOpen										Bangzi	Muyu High	Muyu Mid-High	Muyu Mid	Muyu Mid-Low	Muyu Low
126	112														InstC#-1	InstD-1	InstD#-1	InstE-1	InstF-1	InstF#-1	InstG-1	InstG#-1	InstA-1	InstA#-1	InstB-1	InstC0	InstC#0	InstD0	InstD#0	InstE0	InstF0	InstF#0	InstG0	InstG#0	InstA0	InstA#0	InstB0	InstC1	InstC#1	InstD1	InstD#1	InstE1	InstF1	InstF#1	InstG1	InstG#1	InstA1	InstA#1	InstB1	InstC2	InstC#2	InstD2	InstD#2	InstE2	InstF2	InstF#2	InstG2	InstG#2	InstA2	InstA#2	InstB2	InstC3	InstC#3	InstD3	InstD#3	InstE3	InstF3	InstF#3	InstG3	InstG#3	InstA3	InstA#3	InstB3	InstC4	InstC#4	InstD4	InstD#4	InstE4	InstF4	InstF#4	InstG4	InstG#4	InstA4	InstA#4	InstB4	InstC5
126	113														InstC#-1	InstD-1	InstD#-1	InstE-1	InstF-1	InstF#-1	InstG-1	InstG#-1	InstA-1	InstA#-1	InstB-1	InstC0	InstC#0	InstD0	InstD#0	InstE0	InstF0	InstF#0	InstG0	InstG#0	InstA0	InstA#0	InstB0	InstC1	InstC#1	InstD1	InstD#1	InstE1	InstF1	InstF#1	InstG1	InstG#1	InstA1	InstA#1	InstB1	InstC2	InstC#2	InstD2	InstD#2	InstE2	InstF2	InstF#2	InstG2	InstG#2	InstA2	InstA#2	InstB2	InstC3	InstC#3	InstD3	InstD#3	InstE3	InstF3	InstF#3	InstG3	InstG#3	InstA3	InstA#3	InstB3	InstC4	InstC#4	InstD4	InstD#4	InstE4	InstF4	InstF#4	InstG4	InstG#4	InstA4	InstA#4	InstB4	InstC5
126	114														InstC#-1	InstD-1	InstD#-1	InstE-1	InstF-1	InstF#-1	InstG-1	InstG#-1	InstA-1	InstA#-1	InstB-1	InstC0	InstC#0	InstD0	InstD#0	InstE0	InstF0	InstF#0	InstG0	InstG#0	InstA0	InstA#0	InstB0	InstC1	InstC#1	InstD1	InstD#1	InstE1	InstF1	InstF#1	InstG1	InstG#1	InstA1	InstA#1	InstB1	InstC2	InstC#2	InstD2	InstD#2	InstE2	InstF2	InstF#2	InstG2	InstG#2	InstA2	InstA#2	InstB2	InstC3	InstC#3	InstD3	InstD#3	InstE3	InstF3	InstF#3	InstG3	InstG#3	InstA3	InstA#3	InstB3	InstC4	InstC#4	InstD4	InstD#4	InstE4	InstF4	InstF#4	InstG4	InstG#4	InstA4	InstA#4	InstB4	InstC5
126	115														InstC#-1	InstD-1	InstD#-1	InstE-1	InstF-1	InstF#-1	InstG-1	InstG#-1	InstA-1	InstA#-1	InstB-1	InstC0	InstC#0	InstD0	InstD#0	InstE0	InstF0	InstF#0	InstG0	InstG#0	InstA0	InstA#0	InstB0	InstC1	InstC#1	InstD1	InstD#1	InstE1	InstF1	InstF#1	InstG1	InstG#1	InstA1	InstA#1	InstB1	InstC2	InstC#2	InstD2	InstD#2	InstE2	InstF2	InstF#2	InstG2	InstG#2	InstA2	InstA#2	InstB2	InstC3	InstC#3	InstD3	InstD#3	InstE3	InstF3	InstF#3	InstG3	InstG#3	InstA3	InstA#3	InstB3	InstC4	InstC#4	InstD4	InstD#4	InstE4	InstF4	InstF#4	InstG4	InstG#4	InstA4	InstA#4	InstB4	InstC5
";

    }


}
